version: '2.1'

services:
  thaytuan_duynhan:
    image: thaytuan_duynhan
    build: .
    environment:
      NODE_ENV: development
    ports:
      - 8081:8081
      - 9229:9229
    ## set your startup file here
    command: node --inspect index.js